# Generated by Django 4.2 on 2023-05-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_remove_staff_email_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='number',
        ),
    ]
